baseURL = 'https://kenshinlin.github.io'
# languageCode = 'en-us'
DefaultContentLanguage = 'zh'
languageCode = 'zh-Hans'
title = '啃牛'
theme = 'diary'

[params]
subtitle = '自我觉醒'
# customCSS = true
customJS = true
favicon = './fav.ico'
touchicon = './touch-icon.jpg'
enableGittalk = true

[params.gitalk] 
    clientID = "928350f2c5504cfacdd5" # 您刚才创建Github Application 的 Client ID
    clientSecret = "4b9f508ff2469657d3a8f64e3be48508d9e18693" # 您刚才创建Github Application 的 Client Secret
    repo = "kenshinlin.github.io" # 您的博客的github地址Repository name，例如：xxxx.github.io
    owner = "3109389" # 您的GitHub ID
    admin = "3109389" # 您的GitHub ID
    id = "https://kenshinlin.github.io" # 文章页面的链接地址就是ID
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= true # 设置为true，如果是管理员登录，会自动创建issue，如果是false，需要管理员手动添加第一个评论(issue)
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.


[[menu.main]]
url = "/categories"
name = "Categories"
weight = 3

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1
