baseURL = 'https://kenshinlin.github.io'
# languageCode = 'en-us'
DefaultContentLanguage = 'zh'
languageCode = 'zh-Hans'
title = '啃牛'
theme = 'diary'

[params]
subtitle = '自我觉醒'
customJS = true
favicon = './fav.ico'
# customCSS = true
touchicon = './touch-icon.jpg'
enableGitalk = true
enableTwitterCards = true
disableAutoCollapse = true
description = 'web3,区块链,技术博客,web前端,h5'

[taxonomies]
  tag = 'tags'
  category = 'categories'
  series = 'series'

[params.Gitalk] 
client_id = '928350f2c5504cfacdd5' # 您刚才创建Github Application 的 Client ID
client_secret = '4b9f508ff2469657d3a8f64e3be48508d9e18693' # 您刚才创建Github Application 的 Client Secret
repo = 'kenshinlin.github.io' # 您的博客的github地址Repository name，例如：xxxx.github.io
#owner = "3109389" # 您的GitHub ID
owner = 'kenshinlin'    

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 3

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1
